### ISSUE TITLE
[0.5] Backport "Reading contents&secrets uses specific service account"

### ISSUE THREAD

**Issue by olblak** [rancher/fleet#1297]
Original issue https://github.com/rancher/fleet/pull/1063
QA Template in PR: https://github.com/rancher/fleet/pull/1063#issuecomment-1319763304

**Comment by vivek-infracloud** [comment]
Tested the issue by following the below steps

1. Created a hardened RKE1 cluster with jenkins job.
2. Fleet controller and agent were already present on the cluster.
3. Made sure the cluster is hardened by following the steps [mentioned here].(https://docs.ranchermanager.rancher.io/v2.5/reference-guides/rancher-security/rancher-v2.5-hardening-guides/hardening-guide-with-cis-v1.6-benchmark#set-automountserviceaccounttoken-to-false-for-default-service-accounts).. 
4. Fleet controller and agent version installed on the cluster is - `rancher/fleet:v0.5.2-rc.3` and `rancher/fleet-agent:v0.5.2-rc.3`
5. Ran the [script](https://github.com/rancher/security-scan/blob/fd39c51fd16e522815f244069b497e060e8c5f9c/package/helper_scripts/check_for_default_sa.sh) to verify no roles are bound to the default service accounts. Output of the script is as follows.
```
jq: error (at <stdin>:30): Cannot iterate over null (null)
true
```
6. CIS Scan with `rke-profile-hardened-1.23` profile passes.

If this is expected behaviour this issue can be closed.

**Comment by sowmyav27** [comment]
@vivek-infracloud Can we test an upgrade usecase from 2.5.17 to 2.6-head for the same issue ^. Verify hardened cluster stays and fleet controllers/pods/workloads are good.

**Comment by vivek-infracloud** [comment]
Tested upgrade usecase as mentioned [above](https://github.com/rancher/fleet/issues/1297#issuecomment-1422898888).

1. Created a hardened RKE1 cluster with jenkins job on rancher v2.5.17.
2. The local KRE1 cluster version is v1.20.15.
3. Fleet controller and agent were already present on the cluster.
4. Made sure the cluster is hardened by following the steps [mentioned here](https://docs.ranchermanager.rancher.io/v2.5/reference-guides/rancher-security/rancher-v2.5-hardening-guides/hardening-guide-with-cis-v1.6-benchmark#set-automountserviceaccounttoken-to-false-for-default-service-accounts).
5. Ran the [script](https://github.com/rancher/security-scan/blob/fd39c51fd16e522815f244069b497e060e8c5f9c/package/helper_scripts/check_for_default_sa.sh) to verify no roles are bound to the default service accounts. Output of the script is - `false`
6. CIS Scan with `rke-profile-hardened-1.6` profile fails for test 5.1.5.
7. Upgraded the rancher to v2.6-head.
8. Local cluster version remains same.
9. Ran CIS Scan with `rke-profile-hardened-1.6`. Scans for 5.1.5 and 5.3.2 failed.
10. Followed the steps mentioned [here](https://docs.ranchermanager.rancher.io/v2.5/reference-guides/rancher-security/rancher-v2.5-hardening-guides/hardening-guide-with-cis-v1.6-benchmark#set-automountserviceaccounttoken-to-false-for-default-service-accounts) again. (_**same as Step 4**_)
11. Ran CIS scan, test 5.3.2 passes, test 5.1.5 failed.

**Comment by kkaempf** [comment]
Yes 😉

**Comment by vivek-infracloud** [comment]
Fleet controller and agent version on the cluster after upgrade is observed to be - `rancher/fleet:v0.5.2-rc.3` and `rancher/fleet-agent:v0.5.2-rc.3`. Hence, all good.
