### ISSUE TITLE
[Rancher 2.5.1]Cluster status in Fleet shows "Waitcheckin"

### ISSUE THREAD

**Issue by allaboutopensource** [rancher/fleet#142]
one of the cluster that i have added recently to the rancher 2.5.1 are showing the status as "Waitcheckin
<img width="1387" alt="Screenshot 2020-11-02 at 11 27 28 PM" src="https://user-images.githubusercontent.com/5890851/97902029-fdfaba80-1d62-11eb-916e-6e1a62e3c715.png">
"
gz#14319

**Comment by eumel8** [comment]
/kind bug

Rancher:  2.5.2
Kubernetes: 1.17.6
Kubernetes downstream: 1.18.12
Fleet: 0.3.100 

There are several bugs in this issue.

1. missing https communication to rancher

```
ERRO[0150] error syncing 'fleet-default/c-pzk8b': handler import-cluster: Get "https://rancher.cattle-system/k8s/clusters/c-pzk8b/version?timeout=15s": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers), requeuing
```

fleet-controller wants to talk to rancher via https. If you have previous installation of Rancher, there is no https service listen. You have to expand port range of the service like in newer installation:

```
  - name: https-internal
    port: 443
    protocol: TCP
    targetPort: 444
```

2. Wrong RBAC

```
ERRO[0268] error syncing 'fleet-default/c-sjhvb': handler import-cluster: secrets "fleet-agent" is forbidden: User "u-ake674fua3" cannot delete resource "secrets" in API group "" in the namespace "fleet-system", requeuing
```

The user has only GET verbs, extended it with DELETE and finally the cluster is ACTIVE in the fleet management. The last step has to deeper investigate, because the cluster-role name is u-ake674fua3-**view**, so this has now more rights then view.

compare cluster init process: https://fleet.rancher.io/cluster-overview/

**Comment by jenting** [comment]
I have the same issue at Rancher 2.5.3, the fleet-controller log output:
```
error syncing 'fleet-default/c-q7d9g': handler import-cluster: Get \"https://10.84.73.12/k8s/clusters/c-q7d9g/version?timeout=15s\": dial tcp 10.84.73.12:443: connect: no route to host, requeuing
```

**Comment by NorekZ** [comment]
I have similar problem with Waitcheckin after upgrade to from 2.3.5 to 2.5.3. fleet-controller pod keeps posting this error:

`time="2021-01-04T10:06:33Z" level=error msg="error syncing 'fleet-default/c-rgcw8': handler import-cluster: Get \"https://our-server-name.com/k8s/clusters/c-rgcw8/version?timeout=15s\": x509: certificate signed by unknown authority, requeuing"`

Can somebody help me?

Thanks a lot!

**Comment by GPF-IAG** [comment]
Hi NorekZ, 

Eumel8 ( and of course ibrokethecloud ) were right.  My waitcheckin got fixed by the first reply. Our setup is HA with k3s so you might have to do something different.
In cluster explorer of the local cluster, get a shell, then 

kubectl get svc -A  to show the services
kubectl edit svc rancher -n cattle-system. and add the lines from above.

**Comment by oxr463** [comment]
> Hi NorekZ,
> 
> Eumel8 ( and of course ibrokethecloud ) were right. My waitcheckin got fixed by the first reply. Our setup is HA with k3s so you might have to do something different.
> In cluster explorer of the local cluster, get a shell, then
> 
> kubectl get svc -A to show the services
> kubectl edit svc rancher -n cattle-system. and add the lines from above.

Which lines are you referring to? the https-internal block?

**Comment by GPF-IAG** [comment]
Yep, the https-internal block.

**Comment by lushtech** [comment]
I got the same problem.
![2021-2-5-1](https://user-images.githubusercontent.com/46964559/106995279-8309cb80-67b9-11eb-9e9a-b754f379c198.PNG)
![2021-2-5-2](https://user-images.githubusercontent.com/46964559/106995301-8bfa9d00-67b9-11eb-9d0b-3366ad15e302.PNG)
@GPF-IAG 
can you tell me which lines are you referring to?

**Comment by lushtech** [comment]
@allaboutopensource 
I got some information from [Fleet - fleet-agent fails to deploy in downstream clusters in airgap environment #29036](https://github.com/rancher/rancher/issues/29036).

It seems fleet can not deploy in downstream clusters if you installed rancher in airgap. But in the local cluster it works.

And it wont be fix in the rancher2.5.x according to the post above.

**Comment by yoorock** [comment]
Hi,

I ran into the same problem, which is now solved. I did two things in parallel and cannot tell which one fixed the problem.

1. edited rancher webhook
kubectl edit svc rancher-webhook -n cattle-system

then added the following lines

 - name: https-internal
    port: 443
    protocol: TCP
    targetPort: 444

2. Removed SSL certificate (managed by cloudflare) and re-enabled it.

When it came back to Rancher UI, miracle, the cluster was not in Waitcheckin status anymore

**Comment by simonjcarr** [comment]
@yoorock Thanks so much, your solution worked for me. I am running rancher in a docker container. When I tried to run the kubectl command `kubectl edit svc rancher-webhook -n cattle-system` on my laptop I got the error `rancher-webook` not found.

Instead, I logged into the rancher container on the VM and ran the command in there, it worked a treat. A few seconds later, everything working.

**Comment by SheilaghM** [comment]
This is because Rancher has Fleet controllers trying to communicate with Fleet using the Rancher service IP; but it needs to talk directly to k8s service DNS using service discovery. You need to add this to the no-proxy in Rancher because you don't want this communication going through the proxy.
It's clear in Docker docs, but we need to make it more explicit in Fleet docs.

**Comment by StrongMonkey** [comment]
The right workaround is to add `rancher.cattle-system` into the no-proxy list when installing rancher into airgap environment. https://rancher.com/docs/rancher/v2.6/en/installation/other-installation-methods/behind-proxy/install-rancher/#install-rancher

@jtravee We need to add `rancher.cattle-system` into the no-proxy list in the docs where we run helm upgrade command here https://rancher.com/docs/rancher/v2.6/en/installation/other-installation-methods/behind-proxy/install-rancher/#install-rancher

**Comment by StrongMonkey** [comment]
And we only need to add this to 2.5 docs. We should change the milestone to 2.5.

**Comment by erSitzt** [comment]
@eumel8  do you have any more insight on the RBAC issue ?
I ran into this issue with 2.6.2

Where/How do i change this permission ?
