### ISSUE TITLE
add additional JSON schema validations to CRD for the new fields.

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#1445]
sub-issue of rancher/fleet#1392

CRD generation happens in https://github.com/rancher/fleet/blob/master/pkg/crd/crds.go#L69-L75
We want to have a minimal set of validations for the new fields, toleration, affinity, resources.

After we have a better way to specify JSON schema we can do the more complicated validations.

* (if possible) Define the absolute minimum value for limits, and enforce them via validation. This avoids mistakes that may cause the agents to ends up on a crash loop. 
* (optional) Add CRD validations or at each agent level to make sure that only the defined set of options can be set. Any other option, not specified in the PRD, being set or modified must be rejected.

**Comment by raulcabello** [comment]
## QA Template
 
### Problem
Wrong values can be added to some of the agent config fields in the Cluster custom resources
 
### Solution
Add JSON schema validation, so resources will not be created if they violate any of the restrictions.
 
### Testing
Verify that just these values are supported  `In, NotIn, Exists, DoesNotExist, Gt, Lt` in the following resources:
- `cluster.spec.agentAffinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[].matchExpressions[].operator`
- `cluster.spec.agentAffinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[].matchFields[].operator`
- `cluster.spec.agentAffinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution[].preference.matchExpressions[].operator`
- `cluster.spec.agentAffinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution[].preference.matchFields[].operator`
- `cluster.spec.agentAffinity.podAffinity.requiredDuringSchedulingIgnoredDuringExecution[].labelSelector.matchExpressions[].operator`
- `cluster.spec.agentAffinity.podAffinity.requiredDuringSchedulingIgnoredDuringExecution[].namespaceSelector.matchExpressions[].operator`
- `cluster.spec.agentAffinity.podAffinity.preferredDuringSchedulingIgnoredDuringExecution[].podAffinityTerm.labelSeletector.matchExpressions[].operator`
- `cluster.spec.agentAffinity.podAffinity.preferredDuringSchedulingIgnoredDuringExecution[].podAffinityTerm.namespaceSeletector.matchExpressions[].operator`
- `cluster.spec.agentAffinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution[].labelSelector.matchExpressions[].operator`
- `cluster.spec.agentAffinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution[].namespaceSelector.matchExpressions[].operator`
- `cluster.spec.agentAffinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[].podAffinityTerm.labelSeletector.matchExpressions[].operator`
- `cluster.spec.agentAffinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[].podAffinityTerm.namespaceSeletector.matchExpressions[].operator`

**Comment by sbulage** [comment]
Waiting for parent issue to move to QA sections for review.

**Comment by kkaempf** [comment]
> Waiting for parent issue to move to QA sections for review.

Parent issue got closed in today's planning since it isn't QA-able in itself.

**Comment by sbulage** [comment]
As per the QA template in [comment](https://github.com/rancher/fleet/issues/1445#issuecomment-1521795460).
I am not able to apply affinity rules while importing clusters, as I don't see any option in the UI.

**Initial Steps**
* Used the *imported* cluster.
* Updated the Cluster via UI:
  *  `Continuous Delivery --> Clusters --> Edit YAML` (Select the imported cluster)
* Updated affinity rule mentioned above on the cluster via UI YAML.
  * In order to achieve this I used the labels i.e. applied labels on Node and validated the Operator `In, NotIn, Exists, DoesNotExist, Gt, Lt` worked on `nodeAffinity`
  * Same operators except `Gt and Lt` worked on `podAffinity` rule.

- Here is some changes observed with `fleet-agent` while playing with Operators:
```
satya@opensuse15:~> kubectl get pods -n cattle-fleet-system
NAMESPACE             NAME                                        READY   STATUS        RESTARTS       AGE
cattle-fleet-system   fleet-agent-6ffb4dddf-c2m5s                 1/1     Running       0              3s
cattle-fleet-system   fleet-agent-6c489f6d59-h8zhw                1/1     Terminating   0              36m
```

Applied `Node/Pod affinity` rules even if there is **no label present** and **later added**.
In first case existing pod is in `Pending` state. Once label gets added to respective node then Pod immediately gets created.
