### ISSUE TITLE
Fleet upgrade causes unexpected reboot of app with long path name

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#1509]
### Issue description:
Customer upgrade Rancher from 2.6.6 to 2.6.10.
Then fleet was upgraded also from fleet:100.0.5+up0.3.11 to fleet:100.2.3+up0.5.3.

After the upgrade, some app installed with fleet are rebooted in Downstream cluster.
An app creates PVC of Longhorn and uses it in the Deployment.
After the upgrade, the PVC is recreated and data in the PVC was lost.

By bundle log digging, no OOM found in the pods.
 
This issue does not happen every time. The downstream cluster in which this issue occurs is also different each time.

Customer would like to know root cause of it.

### Repro steps:
 
I made a simple fleet app which creates PVC of Longhorn. You can use by trailing config.
 

Repository URL: https://github.com/masap/fleet-examples
Branche Name: manifests-homma
TLS Certificate Verification: Accept any certificate
Path: single-cluster/manifests-homma

I tried to reproduce it by upgrading Rancher from 2.6.6 to 2.6.10 but it did not occur.
By using my app, customer could reproduce it.

### Workaround:
Is workararound available and implemented? yes
What is the workaround:
Customer can restore the PVC from backup.

### Actual behavior:
PVCs are recreated even after Rancher upgrade on some Downstream clusters. 

### Expected behavior:
PVCs are not recreated even after Rancher upgrade.

**Comment by kkaempf** [comment]
SURE-6234 was updated with new logs

**Comment by kkaempf** [comment]
(JIRA) summary was updated by reporter

**Comment by kkaempf** [comment]
Engineering _can_ reproduce it, back to backlog

**Comment by raulcabello** [comment]
This is happening because the maximum length of the Bundle name changed from 63 to 53 in fleet v0.4.0.
The bundle I created in v2.6.3 (Fleet v0.3.11) has a name of 63 characters: `test-single-cluster-manifests-very-long-name-abcdefghijkl-c4bb5`
Then when I upgrade to v2.6.10 (Fleet v0.5.3) the Bundle name has a maximum length of 53 characters, so it is renamed to `test-single-cluster-manifests-very-long-name-ab-c4bb5`. 
The renaming is causing the reboot of the app. This should not happen when upgrading from Fleet v0.4.0 to any other version. Having a name shorter than 53 characters in Fleet v0.3.11 should prevent the app of being rebooted
