### ISSUE TITLE
Add option to skip bundle targets and customize targeting

### ISSUE THREAD

**Issue by manno** [rancher/fleet#1552]
Users can modify targeting from fleet.yaml:

- [ ] skip a bundle deployment on a cluster (doNotDeploy in fleet.yaml)
- [ ] override the cluster selection from fleet.yaml (overrideTargets in fleet.yaml)

Links:
* https://github.com/rancher/fleet/issues/462
* https://github.com/rancher/fleet/issues/1358
* replaces https://github.com/rancher/fleet/issues/952

**Comment by raulcabello** [comment]
# QA Template

## Problem
The only way to create targets is when defining a `GitRepo`. Targets cannot be modified in Bundles using the `fleet.yaml`

## Solution
- Skip a bundle deployment on a cluster using `doNotDeploy` inside of `targetCustomization` in `fleet.yaml`. Clusters that match won't deploy any resource.
- Override the cluster selection using `overrideTargets` in `fleet.yaml`. Targets defined in the `GitRepo` will be overridden by the targets defined in  `overrideTargets` for this `Bundle`

## Testing

### doNotDeploy

Make sure that resources are not deployed if `doNotDeploy` is true in Clusters that contains the `env: test` label. Verify resources are created if `doNotDeploy` is false.
```
targetCustomizations:
- name: test
  doNotDeploy: true
  clusterSelector:
    matchLabels:
      env: test
```

### overrideTargets

Create a `GitRepo` with a different target that the `overrideTargets`. Verify resources are deployed in the `overrideTargets` and not in the targets defined in the `GitRepo`. Targets from GitRepo should be used if  `overrideTargets` is not provided.
```
overrideTargets:
- clusterSelector:
     matchLabels:
        env: test
```

**Comment by sbulage** [comment]
**QA TEST PLAN for `doNotDeploy`**

Scenarios
|Scenario|Test Case|
|---|---|
|1| Test bundle did not get deploy when `doNotDeploy` value set to `true` option is used in the fleet.yaml|
|2| Test bundle deployed when `doNotDeploy: false` is present in the fleet.yaml|
|3| Test existing bundle gets removed when fleet.yaml updated with `doNotDeploy` with value 'true'|

**Comment by sbulage** [comment]
**REPRO STEPS**

**Scenario 1**
1. Add `doNotDeploy: true` option to the fleet.yaml as added [here](https://github.com/sbulage/test-fleet/blob/main/donot-deploy/fleet.yaml#L4 )
2. Created a `GitRepo` in the UI (https://github.com/sbulage/test-fleet having path `donot-deploy`)
3. Check the bundle is created but resources are not created.
4. Verify that UI will show the Resources(0/0) and Cluster Ready(0/0).
5. Navigate to the Cluster -> Workloads -> deployment.
6. Verified that the deployment is not present for the nginx application.

**Scenario 2**
1. Update `doNotDeploy: false` option to the fleet.yaml as added [here](https://github.com/sbulage/test-fleet/commit/e3be7f24791dce87a364306a1596bde8350918b4)
2. Created a `GitRepo` in the UI (https://github.com/sbulage/test-fleet having path `donot-deploy`)
3. Check the bundle and resources are created.
4. Verify that UI will show the Resources(1/1) and Cluster Ready(1/1).
5. Navigate to the Cluster -> Workloads -> deployment.
6. Verified that the deployment is present in the given namespace for the nginx application.


**Scenario 3**
1. Created a `GitRepo` in the UI (https://github.com/sbulage/test-fleet having path `myapp`)
2. Add fleet.yaml file in the `myapp` with `doNotDeploy: true`
3. Check the bundle remains as it is but resources are deleted.
4. Navigate to the Cluster -> Workloads -> deployment.
5. Verified that the deployment gets removed for the nginx application.

Note: After updating existing `GitRepo` UI shows Resources(1/1) it is known issue and will be fixed by UI team.

**Comment by sbulage** [comment]
**QA TEST PLAN for `overrideTargets`**

Scenarios
|Scenario|Test Case|
|---|---|
|1| Test bundle did not get deploy on the target mentioned in the GitRepo when `overrideTargets` is set in the fleet.yaml|
|2| Test bundle get deploy on the target mentioned in the GitRepo provided that `overrideTargets` is not present in the fleet.yaml|

**Comment by sbulage** [comment]
Scenarios

|Scenario|Test Case|Result|
|---|---|---|
|1| Test bundle did not get deploy on the target mentioned in the GitRepo when `overrideTargets` is set in the fleet.yaml| :white_check_mark:|
|2| Test bundle get deploy on the target mentioned in the GitRepo provided that `overrideTargets` is not present in the fleet.yaml| :white_check_mark:|

**REPRO STEPS**

**Scenario 1**
1. Add `overrideTargets` option to the fleet.yaml as mentioned [here](https://github.com/sbulage/test-fleet/blob/main/overrride-targets/fleet.yaml#L2)
2. Created a `GitRepo` in the UI (https://github.com/sbulage/test-fleet having path `overrride-targets`)
3. Select `Target` `"No Clusters"` in the `Deploy To` section in the UI. 
4. Verify that no bundle or deployment is created because there is no target mentioned.
5. Verify that UI will show the Resources(0/0) and Cluster Ready(0/0).

>Info: It will not show any resources created because label is not present on the cluster.

**Scenario 2**
1. Add `overrideTargets` option to the fleet.yaml as mentioned [here](https://github.com/sbulage/test-fleet/blob/main/overrride-targets/fleet.yaml#L2)
2. Created a `GitRepo` in the UI (https://github.com/sbulage/test-fleet having path `overrride-targets`)
3. Select `Target` `"No Clusters"` in the `Deploy To` section in the UI. 
4. Verify that no bundle or deployment is created because there is no target mentioned.
5. Verify that UI will show the Resources(0/0) and Cluster Ready(0/0).
6. Set the label on the downstream cluster (`label: override`)
7. Verify that UI will show the Resources(1/1) and Cluster Ready(1/1) 

> Info: `overrideTargets` overriden the target added by `GitRepo` and created the resources.

8. Navigate to the Cluster -> Workloads -> deployment.
9. Verified that the deployment is present in the given namespace for the nginx application.

**Comment by freimer** [comment]
This feature is broken on the latest rancher/fleet.  We have this:
```yaml
targetCustomizations:
  - name: app2
    clusterSelector:
      matchLabels:
        wavetest-app2: 'true'
    correctDrift:
      enabled: true
      force: true
  - name: notapp
    clusterSelector: {}
    doNotDeploy: true
    correctDrift:
      enabled: true
      force: true
```
The bundle is not deployed on clusters that do not have the wavetest-app2 label set to 'true'.  When we label the cluster, it deploys the bundle.  However, when we remove the label, the bundle / app is not removed from the cluster.

**Comment by freimer** [comment]
I believe the bundledeployment created for the cluster is not being removed.  If we manually delete it, the app is removed, and with a force update i is not recreating the bundle/app because the cluster does not have the required label.  So why is rancher/fleet not deleting the bundledeployment when the targetCustomization no longer matches?

**Comment by freimer** [comment]
In this change here:
https://github.com/rancher/fleet/pull/1580/files#diff-856a59abc02ce584692f9efab1cdecf832ec1908476f7a5321af151eaae38c81

we see where the bundledepoloyment _creation_ is skipped if DoNotDeploy is true:
![image](https://github.com/user-attachments/assets/1f512aac-157d-4241-9a82-6518ad1e9457)

But there is nothing to delete a bundledeployment if it was previously deployed/created.  We need something in here to delete the bundledeployment if it is true and the bundledeployment exists, not just log a message and continue on...

**Comment by freimer** [comment]
Chat suggested something like this as a fix:
```go
if targetCustomization.DoNotDeploy {
    log.Infof("Skipping deployment to cluster %s because doNotDeploy is set to true", cluster.Name)

    // Check if a BundleDeployment exists for this cluster
    bundleDeploymentName := generateBundleDeploymentName(bundle.Name, cluster.Name)
    existingBundleDeployment, err := bundleDeploymentLister.Get(namespace, bundleDeploymentName)
    if err == nil && existingBundleDeployment != nil {
        // If a BundleDeployment exists, delete it
        log.Infof("Deleting existing BundleDeployment %s for cluster %s", bundleDeploymentName, cluster.Name)
        err := bundleDeploymentClient.Delete(namespace, bundleDeploymentName, &metav1.DeleteOptions{})
        if err != nil {
            log.Errorf("Failed to delete BundleDeployment %s: %v", bundleDeploymentName, err)
        }
    } else if err != nil && !errors.IsNotFound(err) {
        log.Errorf("Error checking for existing BundleDeployment: %v", err)
    }

    return nil
}
```
I have no idea if that is correct or just a huge hallucination, but it may help.

**Comment by freimer** [comment]
@manno can you take a look at my comments here?  Not sure if you, or anyone, gets pinged on a closed case.  It looks like we need some changes to delete a BundleDeployment if one exists and the target customization is updated to now doNotDeploy on a cluster.  That is simply not done currently (or at least with the patch referenced).

I can open a _new_ issue and copy/paste all this if you want.
