### ISSUE TITLE
Update release notes about targetCustomizations

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#1705]
The [[Request entity too large: limit is 3145728](https://github.com/rancher/fleet/issues/1650) bug can't easily be fixed and thus needs a fix/workaround within the git repo.

This needs to be mentioned in the release notes.

**Comment by manno** [comment]
Bundles that use a target customization to modify helm chart URLs or versions for some clusters can produce custom resources that are too large for the API. 
Each path in a GitRep is converted into a bundle. The bundle contains all the downloaded helm charts, by using target customizations to download multiple versions, the bundle size increases.

As a workaround multiple paths can be used instead of target customizations. This is also the more declarative approach, but it comes at the cost of some duplication.
Target customization that do not modify the chart URL or version are not affected.

**Comment by martyav** [comment]
@manno How do users set up multiple paths instead of target customization? Is this something inside Fleet instead of Rancher?

**Comment by manno** [comment]
@martyav 

They would have to restructure their git repos. Instead of one bundle with multiple versions, via target customizations, I would suggest to copy that folder once per version and create multiple gitrepo resources.
In Fleet 0.8 it would be possible to use one gitrepo and adapt targeting per path.

In practice I don't think many users actually use the target customization to customize helm chart versions. And even if they do, it's no problem unless the helm charts are huge.
