### ISSUE TITLE
Spike: Fleet At Scale

### ISSUE THREAD

**Issue by manno** [rancher/fleet#1739]
* [ ] how to set up a large fleet
* [ ] how to measure performance
* [ ] which scenarios to measure
* [ ] initial measurement of current state (naive) 

Timeboxed: medium (days)

Register 20-1000 clusters in fleet and observe the performance.

* clusterregistrations
* deploying bundles
* what about a hundred bundles?
* clusters in different namespace, same namespace
* failing bundles
* status reporting 
* possible benchmark test that runs on schedule
* rollout partition with more than 50 targets work? (`MaxNew` constant)

**Comment by manno** [comment]
See https://github.com/rancher/fleet/pull/1659 for concerns regarding cluster import/manageagent.

**Comment by manno** [comment]
https://github.com/manno/fleet-dev-tools/blob/main/bin/20.sh

**Comment by aruiz14** [comment]
After talking to @p-se, we have agreed on a few first steps that get us moving forward:
- We want to setup a Kubernetes cluster with a dedicated node where to run the Fleet (via deployment affinity rules). This will allow us to isolate the controller from other possible noisy neighbors and control the compute resources used by the controller.
- Having monitoring of the service will provide useful insights on the experiments we run, so we could install Prometheus (and maybe Grafana?), as well as using a modified version of Fleet adding the necessary instrumentation. This will allow us to also inspect and correlate Kubernetes metrics as well.
- In addition to running k3d locally, we can explore other options like:
  - Running `k3s` as Pods?
  - [`controller-runtime/pkg/envtest`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/envtest#AuthenticatedUser) ([more docs](https://book.kubebuilder.io/reference/envtest.html))
  - Something like virtual or nested clusters:
    - https://github.com/loft-sh/vcluster
    - https://github.com/kubernetes-sigs/cluster-api-provider-nested
  - Other lightweight cluster "simulators", like https://github.com/kubernetes-sigs/kwok. This may not work for cases where a real `fleet-agent` needs to be running, could work for simpler workflows like registration.
- Define a set of test cases that are likely to become bottlenecks and runs some benchmarks to determine the failure point:
  - Cluster registrations (at multiple creation paces).
  - Different variations of bundle numbers and number of downstream clusters.

**Comment by p-se** [comment]
# Fleet at Scale

## How to set up a large fleet?

What a large cluster is depends on its definition. If a large fleet
means having hundreds or thousands of clusters, then there are limited
options to achieve that:

-   Using cloud providers such as AWS, GCP, Azure, Digital Ocean, etc.

-   Using a local service, if the hardware is available (which we have
    not had).

-   Running those clusters locally but emulating the downstream clusters
    (by emulating the behavior of the downstream agents).

Only if large means not having hundreds or thousands of downstream
clusters, we can run fleet locally for naïve testing. This is what the
naïve setup is about.

### Naïve Setup (local)

The purpose of the naïve setup needs to be made clear upfront. **This
setup cannot be used to test fleet at scale.** It can only be used to
test basic functionality of fleet managing downstream clusters to a very
limited extent. However, for testing that fleet does not break in
certain simple scenarios, we have created two environments. The first
one was created on Linux, the second one on Mac. However, the k3d setup
has also been tested on Mac, whereas the Colima setup has not been
tested on Linux but may work as well.

-   K3d setup using K3s and Docker (with embedded etcd)

-   Colima + Minikube using containerd & etcd-based Kubernetes

Both setups come with the same ready-to-use instructions on how to
deploy a monitoring stack using Grafana, Prometheus and a few necessary
exporters and carefully selected Grafana dashboards. The setup of
monitoring using those instructions is automated and even takes care of
the necessary configuration automatically.

#### K3d setup

The fleet-at-scale repository contains a \`setup\` script which creates
the k3d environment. The same repository contains some naïve tests in
the \`tests\` folder.

-   bundle-ready-helm

-   bundle-ready-simple (which just deploys a ConfigMap)

-   cluster-nonready

"ready" and "nonready" in this context describe the expected states of
the objects. Since no real downstream clusters are created at this
scale, the state of those objects is expected not to be ready, whereas
the other tests create valid objects and hence expected to become ready.

##### Limitations

-   Due to the hardware limitations of a local environment, there is a
    limit in the number of containers which can be run locally, hence
    the number of local downstream clusters that can be created needs to
    be limited.

-   CPU and network usage in a local setup are too different from a
    production environment to yield results which can be used as
    reliable results for testing fleet "at scale".

-   Running tests locally at a certain size result in significant strain
    on the disk and leads to high CPU usage just due to the resulting IO
    wait.

##### Observations

-   Independent of the conducted test, the fleet controller did not
    consume extensive CPU time nor memory. It rather appeared that the
    heavy lifting is not done by the fleet controller.

-   However, extensive creation of objects leads to a surprisingly
    sustained CPU usage for a few minutes. This behavior has been
    observed by creating "fake" cluster objects as well as by creating
    Bundle objects.

### Remote Setup (repeatable and reliable results)

The remote setup is what we have evaluated to be a necessary environment
to be able to conduct **repeatable**, **reliable** and **comparable**
tests. In other words, this is the recommended setup for creating a
baseline which can be used to monitor the performance of Fleet in
different scenarios and make that comparable. For this, certain criteria
need to be fulfilled.

-   It needs to be ensured that the testing machines continuously have
    the same specifications for running the tests, e.g., tests conducted
    on a cloud provider should make sure the machines on which the tests
    run are always of the same size and have the same performance
    characteristics.

-   Measurements can only reliably be compared if the test cases for
    which the data has been gathered are compared and are equivalent.

## How to measure performance?

Measuring the performance of fleet is possible using different ways, but
we have mainly focused our investigation on

-   Monitoring and

-   Profiling.

Profiling appears to be the most appropriate way to investigate
performance issues which have already surfaced, whereas monitoring
appears to be the most appropriate way to find them in the first place
and perhaps narrow down the high-level cause of it (for it to perhaps be
profiled). Naturally, we've decided for monitoring to be used when tests
of certain scenarios in Fleet are to be conducted and persisted. We have
decided to use Prometheus for collecting the data and Grafana for
visualizing it.

### Performance metrics

The currently integrated Grafana Dashboards are the following.

-   API server dashboard

-   Kubernetes Pod metrics (CPU, Memory and Network)

### How to share the data from the measurements?

-   Screenshots (most shareable, inspection capabilities most limited)

-   Grafana Snapshots (requires a Grafana instance, but allows to
    inspect data without having to have the corresponding data source on
    which the snapshot has been created)

-   Prometheus Snapshots (most complete data dump, most difficult to
    re-use, share or setup)

-   For the sake of comparability, we need to have aggregated data to
    compare. In this case, we suggest creating a summary of certain key
    values (e.g., high/low/average CPU & memory, duration of running
    tests, etc), persist them (in a table) and use them for comparing
    the results of different test runs.

### How to persist all of the data from the measurements?

-   Shared Prometheus instance (would still require knowing the labels
    of the collected data and the timestamp)

-   Prometheus Snapshots (possible limitation in "importing" this into a
    single TSDB, at least using Prometheus, setup is more difficult,
    sharing is inconvenient). The benefit of this approach however is
    that it does contain all the measured data and that this data is
    restorable.

## Which scenarios to measure?

Those are the suggestions for tests which could be implemented. Some of
those tests might make sense to be tested in the naïve environment
whereas others might only make sense to be tested in the elaborate
environment. This does not exclude the fact that it might make sense to
have certain in both.

-   ClusterRegistrations

-   deploying bundles

-   what about a hundred bundles?

-   clusters in different namespace, same namespace

-   failing bundles

-   status reporting

-   rollout partition with more than 50 targets work? (MaxNew constant)

-   Remote environment

-   Additional descriptions

-   Register 20-1000 clusters in fleet and observe the performance.

## Initial measurements of current state (naive)

Reliable and comparable measurements require an environment that is
remote and isolated, can be re-created and thus makes the results
comparable.

Since the naive environment we have created cannot be used to reliably
determine performance metrics, we have merely collected thoughts about
how this would be done in a future implementation for the elaborate
setup.

However, it is possible to create "empty" Cluster objects that result in
the creation of all the related resources (namespace and RBAC, Bundles
and BundleDeployments). While this does not accurately represent the
reality (in which fleet-agent would be performing updates in those same
objects that are watched by the controller), this may still be useful to
measure memory and CPU usage on an idle system, e.g., base memory usage
based on the number of Bundle objects.

### How to get some data for comparison (benchmark)

In addition, while most of users interact with fleet by adding GitRepo
objects, we can also skip this step and directly create Bundle objects.
This eliminates a possible source of noise and delays, while keeping the
focus on the fleet-controller, as GitRepos are managed by a different
controller anyway. Comparing metrics from monitoring can be challenging
when doing so programmatically. Having a Grafana dashboard and
evaluating those results manually is simpler than coming up with a way
to have that done automatically. However, to be able to compare values
programmatically, it is necessary to have certain metrics anyhow. We
suggest concentrating on a few key metrics for which certain
aggregations are applied upon (min/max/avg) to make them comparable.

In detail, this could mean querying Prometheus using PromQL for the CPU
usage of the controller and memory consumption of the time the test was
running. The duration of the tests should also be persisted. Those
metrics can then be used as the first baseline for comparison the
performance development of fleet at scale.

## Suggested follow-up stories

Repeatable, reliably and comparable benchmarks (baseline)

**Comment by p-se** [comment]
https://github.com/rancher/fleet/issues/1850
