### ISSUE TITLE
Prevent deletion of CRDs by Fleet

### ISSUE THREAD

**Issue by weyfonk** [rancher/fleet#1844]
A `GitRepo` resource may point to a git repository where _Custom Resource Definitions_ are specified as K8s manifests. Those CRDs would then be included in bundles generated by Fleet.

In some cases, re-deploying those CRDs can have unwanted side effects such as loss of connectivity, for instance if those CRDs represent [ingress routes](https://doc.traefik.io/traefik/v2.2/routing/providers/kubernetes-crd/).

On the other hand, Helm can [skip](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/) deployment of CRDs which already exist.

A solution could consist in implementing a new `enableCRDDeletion` (boolean flag) at `GitRepo` level, which would resolve to `false` by default.

**Comment by manno** [comment]
Let us also  check if there is a problem with updating CRDs, does it work with `crds/` and/or `template/` folder?

**Comment by manno** [comment]
See https://github.com/rancher/fleet/pull/2028

**Comment by 0xavi0** [comment]
I've been investigating this one and I think we don't need to implement anything as the feature was implemented in this PR: https://github.com/rancher/fleet/pull/2028

The default behaviour would be to NOT delete CRDs and just delete them if `deleteCRDResources` is set to true.

I've been also testing different scenarios and we should maybe reflect things in the documentation.

* **Scenario1 - CRDs are located in the templates folder -  deleteCRDResources = true**
In this case CRDs are deployed when applying the gitrepo and deleted when the gitrepo is deleted
I used [this example](https://github.com/0xavi0/fleet-examples/tree/test-helm-crds/single-cluster/helm-crds2) setting deleteCRDResources = true

* **Scenario2 - CRDs are located in the templates folder -  deleteCRDResources = false**
In this case CRDs are deployed when applying the gitrepo and KEPT when the gitrepo is deleted
I used [this example](https://github.com/0xavi0/fleet-examples/tree/test-helm-crds/single-cluster/helm-crds2) setting deleteCRDResources = false

* **Scenario3 - CRDs are located in the crds folder -  deleteCRDResources = true**
CRDs are deployed when applying the gitrepo and KEPT when the gitrepo is deleted
I used [this example](https://github.com/0xavi0/fleet-examples/tree/test-helm-crds/single-cluster/helm-crds1) setting deleteCRDResources = true

* **Scenario4 - CRDs are located in the crds folder -  deleteCRDResources = false**
CRDs are deployed when applying the gitrepo and KEPT when the gitrepo is deleted
I used [this example](https://github.com/0xavi0/fleet-examples/tree/test-helm-crds/single-cluster/helm-crds1) setting deleteCRDResources = false

* **Scenario5 - CRDs already exist, are located in the crds folder of the chart -  deleteCRDResources = true**
In this case CRDs were not re-deployed, and are KEPT after gitrepo is deleted
I used [this example](https://github.com/0xavi0/fleet-examples/tree/test-helm-crds/single-cluster/helm-crds1) setting deleteCRDResources = true and the same crds you can find the the crds folder

* **Scenario6 - CRDs already exist, are not in the crds folder, deploy gitrepo, delete gitrepo, deploy gitrepo - deleteCRDResources = false**
CRDs are deployed in the first gitrepo deployment, KEPT when gitrepo is deleted and NOT RE-DEPLOYED when gitrepo is deployed.
I used [this example](https://github.com/0xavi0/fleet-examples/tree/test-helm-crds/single-cluster/test-crds-cert-manager)

So... when CRDs are in the crds folder CRDs are always kept and not re-deployed.
I've been checking the code in https://github.com/rancher/fleet/pull/2028 and I think `helm` treats different CRDs that are in the crds/ folder, those are not passed to the PostRenderer [here](https://github.com/rancher/fleet/blob/df33a26f5c4cc021355914428e5247873ced1ba3/internal/helmdeployer/postrender.go#L35), so `helm` treats those different from the rest of resources.

I think the feature was already implemented for CRDs that are not located in the crds/ folder in https://github.com/rancher/fleet/pull/2028 and it works as expected when CRDs are located in the crds/ folder because `helm` treats them as a special case.
