### ISSUE TITLE
Support helm repo under HTTP provy

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/fleet#230]
Placeholder for https://github.com/rancher/gitjob/issues/24

**Comment by jiaqiluo** [comment]
waiting for fleet `v0.3.4-rc1`

**Comment by jiaqiluo** [comment]
The bug is reproduced on v2.5.5 HA setup running behind a proxy 

Steps:
- setup a proxy server
- create 3 EC2 instances that do not have public IP
- configure docker demon on those instances to use the proxy
- use RKE CLI (v1.2.4) to provision a 3-node all-role cluster 
- follow Rancher's documentation to install Rancher v2.5.5 into the cluster. Pass the proxy parameters in the helm command like the following:
```
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --version v2.5.5 \
  --set hostname=your-hostname \
  --set proxy="http://your-proxy-sever:port" \
  --set noProxy="127.0.0.0/8\,10.0.0.0/8\,172.16.0.0/12\,192.168.0.0/16\,.svc\,.cluster.local"
```
- wait for Rancher to be up
- go to `Cluster Explorer` -> `Continues Delivery` -> `Git Repos` -> add a new `git repo` which will use an external Helm repo. I used the example from Fleet's example repo: https://github.com/rancher/fleet-examples/tree/master/multi-cluster/helm-external
```
URL: https://github.com/rancher/fleet-examples
branch: master
path: multi-cluster/helm-external
```
![image](https://user-images.githubusercontent.com/6218999/107836877-dcdf3800-6d5b-11eb-9213-c5c2a605c9df.png)


Results:
- the gitRepo is failed at the state `Git Updating`
![image](https://user-images.githubusercontent.com/6218999/107836962-2760b480-6d5c-11eb-9a4d-aba0b05e4e7c.png)
- and see the following error on the detail page 
![image](https://user-images.githubusercontent.com/6218999/107837002-49f2cd80-6d5c-11eb-98b5-b854492a6014.png)

**Comment by jiaqiluo** [comment]
The bugfix is validated on Rancher `v2.5-head` dba3321

The steps are the same as in my previous comment.  Notice that `fleet:0.3.400-rc05` is used by default.

![image](https://user-images.githubusercontent.com/6218999/107837269-575c8780-6d5d-11eb-8ab4-eaef4c86d627.png)


Results:
- the `gitRepo` is added and active 
- 
![image](https://user-images.githubusercontent.com/6218999/107837213-2b410680-6d5d-11eb-952e-df19a2c7b838.png)

- no error shows anymore 
- 
![image](https://user-images.githubusercontent.com/6218999/107837187-0fd5fb80-6d5d-11eb-8924-a1876456169e.png)
