### ISSUE TITLE
Using an invalid chart name in fleet.yaml results in an unexpected state of the repo

### ISSUE THREAD

**Issue by janeczku** [rancher/fleet#2547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Fleet displays an incorrect repo state: "This git repo is not targeting any clusters". 

There is not a single event or error message to indicate that something is wrong with the helm chart referenced in the fleet.yaml.

### Expected Behavior

Fleet shows an error message. The error message and the event should contain the information required to identify the root cause (invalid chart name in the fleet.yaml).

### Steps To Reproduce

1) Create a new git repo resource in Git, targeting one or more clusters
2) Reference a git repo that contains a fleet.yaml referencing an external helm chart with an invalid name (e.g. the chart does not exist in the repo).

```
defaultNamespace: grafana
helm:
  releaseName: grafana-release
  repo: https://grafana.github.io/helm-charts
  chart: unknownchart
  version: 7.3.8
```

Following repo could be used for reproducing the issue:

Git repo URL: https://github.com/janeczku/fleet-demo.git
Git repo path: /single-cluster/helm-ext

### Environment

```markdown
- Architecture: x86-64bit
- Fleet Version: v0.9.0 / Rancher 2.8.2
```

### Logs

```markdown
Log from fleet-agent pod in fleet-default namespace:

HOSTNAME=grafana-broken-6d1b6-jh4sg
2024-06-21T04:16:12.652896649-04:00 KUBERNETES_PORT_443_TCP_PROTO=tcp
2024-06-21T04:16:12.652902034-04:00 COMMIT=01c65ed79a5ef30dfced4e7af92cbd51fe00cd90
2024-06-21T04:16:12.652904908-04:00 KUBERNETES_PORT_443_TCP_ADDR=10.43.0.1
2024-06-21T04:16:12.652907818-04:00 KUBERNETES_PORT=tcp://10.43.0.1:443
2024-06-21T04:16:12.652911029-04:00 PWD=/workspace/source
HOME=/fleet-home
2024-06-21T04:16:12.652917126-04:00 KUBERNETES_SERVICE_PORT_HTTPS=443
2024-06-21T04:16:12.652919984-04:00 KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP=tcp://10.43.0.1:443
SHLVL=1
2024-06-21T04:16:12.652928668-04:00 KUBERNETES_SERVICE_PORT=443
EVENT_TYPE=
2024-06-21T04:16:12.652934439-04:00 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
2024-06-21T04:16:12.652937170-04:00 KUBERNETES_SERVICE_HOST=10.43.0.1
2024-06-21T04:16:12.652940221-04:00 _=/usr/bin/env
time="2024-06-21T08:16:13Z" level=fatal msg="no chart name found"
```

### Anything else?

<img width="1143" alt="Bildschirmfoto 2024-06-21 um 10 12 21" src="https://github.com/rancher/fleet/assets/3813921/ca0dcb7b-95c3-4084-84cd-6528c463fa23">
<img width="1153" alt="Bildschirmfoto 2024-06-21 um 10 12 17" src="https://github.com/rancher/fleet/assets/3813921/b9e892f4-437e-4667-b497-93492e381f4c">

**Comment by 0xavi0** [comment]
This has been fixed in 2.9, as the `gitjob` is only executed 3 times in case of error and then updates the `GitRepo` status.
`2.8` is restarting the `gitjob` all the time and resets the status.
It is possible that the user is able to see the error in the UI with `2.8` for a fraction of time, but is obviously not ideal.

I can recreate with `2.8.2` 


![Image](https://github.com/rancher/fleet/assets/96239481/74e869e0-e0ba-4bb2-af6f-42fb28ef0484)



But, when using the same `GitRepo` in `2.9` I can see the error in the UI.


![Image](https://github.com/rancher/fleet/assets/96239481/21b1b022-c007-4334-91b0-7eaee6854696)

![Image](https://github.com/rancher/fleet/assets/96239481/d9b08117-8f70-4f4e-a84e-1d49e2b55776)


I also find the `This git repo is not targeting any clusters` message in the UI a bit confusing, but that's not related with `fleet`.
When having any issue with the `GitRepo`, as it could not be applied to any cluster the UI is showing that message. 

I'm closing the `fleet` related issue as it is fixed in `2.9`
