### ISSUE TITLE
Q: How do partitions work?

### ISSUE THREAD

**Issue by strowi** [rancher/fleet#2891]
Hi,

we recently stumbled upon DDoS-ing our registry by not having any partitions/rolloutstrategy. I was wondering what happens with the following rolloutStragegy:

Let's say we have 200 clusters of which always one or two handful are offline.

```
rolloutStrategy:
  maxUnavailable: 100%
  maxUnavailablePartitions: 100%
  autoPartitionSize: 10%
```

How will the rollout happen here? Still one partition (20 clusters) after the other?
Or just all at the same time since 100% are allowed to fail?

Is there another way to insert some delay between rollouts to prevent the DDoS of our registry?

Thx,
strowi

**Comment by weyfonk** [comment]
Duplicate of #2672. This could be a good use case to document there.

**Comment by p-se** [comment]
If the GitRepo targets 200 or more clusters, autoPartitionSize will be honored. Everything below that disables auto-partitioning and (internally) puts all clusters into a single partition.

By setting 

```
  maxUnavailable: 100%
  maxUnavailablePartitions: 100%
```

every mechanism that would pause the deployment until the deployed instances become ready is disabled. At this point this is all we have to delay execution of deployments to prevent the deployments from pulling container images all at once.

> How will the rollout happen here? Still one partition (20 clusters) after the other?
Or just all at the same time since 100% are allowed to fail?

Technically there will be 10 partitions with 20 clusters each, which will be processed in order. But since no constrains are defined, this will happen quite quickly and result in it appearing to have happened all at the same time.

If you want to make sure that those 20 clusters of a partition are the limit of what is allowed to happen at once, you need to set

```
  maxUnavailable: 0
  maxUnavailablePartitions: 0  # the default and crucial to be set in this case
```

But since this will not allow any cluster to have a non-ready deployment, you might want to adapt `maxUnavailable` to something a bit higher. If you set it to `1`, the second partition will start to be processed once 19 of the 20 clusters have reported their deployments to be ready, since the value of `maxUnavailable` will also be used to evaluate when all partitions are considered ready. That means if 19 of 20 clusters are ready, the partition will be considered ready and the deployment will continue, even though `maxUnavailablePartitions` is set to `0`.

You can have more influence on when a partition is considered ready if you use manual partitioning. But unlike what we have documented currently, those clusters that are not part of the manually configured partitions will not be added to end of the list of partitions.

> Let's say we have 200 clusters of which always one or two handful are offline.

Please also note that every offline cluster that is targeted by the GitRepo and its partitions is one cluster that will not report ready, so you will need to account for that in your `maxUnavailable` setting.

If you want to go slower, I recommend you decrease the `autoPartitionSize` further. If you have less than 200 targeted clusters (on- or offline), you will need to configure the partitions manually.

**Comment by strowi** [comment]
@p-se thank you for the thorough explanation. ;)

Sadly this is what i thought initially, either we need to group the devices differently (as we don't really know which ones might be a problem "this" time) or scale our registry. Some manually configurable delay between devices/partitions would be really helpful.

**Comment by p-se** [comment]
Setting 

```
rolloutStrategy:
  maxUnavailable: 2 # or something similarly low
  maxUnavailablePartitions: 0  # the default and crucial to be set in this case
  autoPartitionSize: 1%  # puts two clusters into one partition
```

puts every two clusters into their own partition. This means that we evaluate `maxUnavailable` after every two clusters, whereas `maxUnavailable: 2` means that two clusters are deployed to at the same time. That would limit the amount of simultaneous downloads from an OCI registry quite effectively. The only case in which this won't work well is if you expect to have many clusters that won't become Ready _and_ you still want to make sure that all clusters are deployed to. In that case you can only limit the parallelism to the amount of deployments that you expect and allow to fail.
