### ISSUE TITLE
[SURE-9311] Fleet's gitrepoJobsCleanup not disabled when continuous-delivery (Gitops) feature is off

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#3054]
### Request description:
We have the continuous-delivery feature turned off on our rancher installation. When upgrading to rancher v2.9.3 (fleet v0.10.4) a new cronjob is created on the local cluster that generate failing jobs.

We've been able to turn off the cronjob creation by specifying "fleet" values in rancher's chart (i.e.: https://github.com/rancher/rancher/blob/main/chart/values.yaml#L200) and it all seems fine, but the warning about "override all other global values" might cause issues in later versions...

Would it be possible to set the default fleet chart value for `migrations.gitrepoJobsCleanup` based on the feature flag? Same way it is for the feature itself here: https://github.com/rancher/rancher/blob/main/pkg/controllers/dashboard/fleetcharts/controller.go#L121

### Actual behavior:
Fleet cronjobs being created when fleet is disabled

### Expected behavior:
No fleet cronjobs being created when fleet is disabled.

### Workaround:
Is a workaround available and implemented? yes
What is the workaround:

We've been able to turn off the cronjob creation by specifying "fleet" values in rancher's chart (i.e.: https://github.com/rancher/rancher/blob/main/chart/values.yaml#L200) and it all seems fine, but the warning about "override all other global values" might cause issues in later versions...

**Comment by weyfonk** [comment]
* [ ] forward-port to v0.11
* [ ] forward-port to `main`

**Comment by sbulage** [comment]
### System Information

| Rancher Version | Fleet Version |
|--------|--------|
| **v2.9-b8239f00fb45d7bfcfc31b2b6a8d7c8a20f755bf-head** | **fleet:v0.10.7-rc.2** | 

### Steps Performed 

- Installed **Rancher Prime 2.9.2**
- **Deactivated** the Continuous Delivery option from the UI.
- Upgraded to **Rancher Prime 2.9.3** and saw that Fleet version 0.10.4 installed (by refreshing Repositories.)
- Observed that **Crontab** **gitrepoJobsCleanup** job is created in the local cluster which could be executed daily but no Fleet installed.
- Upgraded Rancher to 2.9-head version where the fix is added in the version: **0.10.7-rc.2**
- Saw that **Crontab** **gitrepoJobsCleanup** was removed from the cluster as Continuous Delivery option is disabled in the UI.

- Also, observed that After activating Continuous Delivery from UI, saw that **Crontab** job for **gitrepoJobsCleanup** is added back.
