### ISSUE TITLE
fleet agent stuck in Uninstalling state on an upgraded rancher setup

### ISSUE THREAD

**Issue by sowmyav27** [rancher/fleet#362]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- On 2.5.7, deploy a cluster (In my case it was a windows cluster)
- Upgrade to 2.5.8-rc19
- Fleet agent on the downstream cluster is seen stuck in uninstalling state in cluster explorer --> Installed Apps page

<img width="1637" alt="Screen Shot 2021-05-05 at 11 11 24 AM" src="https://user-images.githubusercontent.com/26032343/117194676-3a9e8180-ad99-11eb-85f1-e9ff2df35f97.png">

**Expected Result:**
It should get deleted.

**Other details that may be helpful:**
On manually deleting it, the agent is deleted from cluster explorer

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.8-rc19
- Installation option (single install/HA): Single
(paste the output here)
```

**Comment by StrongMonkey** [comment]
After talking to denise we are going to put a release note that this is a special case during the upgrade from 2.5.(0-7) to (2.5.8 or later). We can just mention that this is the expected behavior and there is no harm to delete the app from marketplace since it is no longer used.

@sowmyav27 Can we also make sure you don't see this for upgrade from rancher 2.5.8 to 2.6 later after a new fleet rc is tagged?

**Comment by sowmyav27** [comment]
**On an upgrade from 2.5.8 to master- commit : `2b50005ae`**

- This issue is not seen. 
- Fleet is seen installed in `cattle-fleet-system` namespace now
- Fleet version: `fleet:100.0.0+up0.3.6-rc2`
