### ISSUE TITLE
Add wait-for-jobs arg

### ISSUE THREAD

**Issue by svahn** [rancher/fleet#364]
Add support for the new argument "wait-for-jobs" for helm install and upgrade that solves the issues described in [#5948](https://github.com/helm/helm/issues/5948).

**Comment by raulcabello** [comment]
@rancher/qa
 
### Problem
There is no way to wait for jobs completion before marking a `GitRepo` as ready. As soon as the job launches the job is considered as ready.
 
### Solution
Use the waitForJobs parameter in helm. From helm docs:
```
--wait-for-jobs  -> if set and --wait enabled, will wait until all Jobs have been completed before marking the release as successful. It will wait for as long as --timeout
```
`waitForJobs` can now be specified in the `fleet.yaml`. It will wait until the job is finished to mark the `GitRepo` as `Ready`. Notice that you need to provide a `timeoutSeconds` in the `fleet.yaml` otherwise the waitForJobs will be ignored.
 
### Engineering Testing
#### Manual Testing
I created a [repo](https://github.com/raulcabello/fleet-test/tree/main/job) that contains a job that sleeps for 60 seconds for testing.
Create a new `GitRepo` pointing to https://github.com/raulcabello/fleet-test/tree/main/job
Verify that the `GitRepo` is in `WaitApplied` state until the job finishes, then it become Ready.

Any other repo can be used for verification as long as it sets the `waitForJobs` to true and have the `timeoutSeconds`  in the helm section of the `fleet.yaml`

**Comment by deniseschannon** [comment]
Re-opening for QA validation. @kkaempf Please apply the appropriate labels as necessary to get this over to QA. 

Also, what is the expectation for this option being exposed in Rancher? Is it planned or expected?

**Comment by kkaempf** [comment]
Documentation: https://fleet.rancher.io/next/gitrepo-structure#fleetyaml

**Comment by sowmyav27** [comment]
This is not ready to test as this will need a Fleet RC to test

**Comment by sbulage** [comment]
Verified first two test cases QE Test Plan in above comment.
```
Rancher Version: 2.7.5-rc1
fleet version: 0.7.0-rc.2
```

**TEST RESULT**

Scenarios
|Scenario|Test Case| Result
|---|---|---|
|1|Test ability to check `waitForJobs` for `GitRepo` as `Ready` until the wait for job is finished. Verify that `sleep` time in `container` is less than `timeoutSeconds: 120` in seconds, mentioned in the `fleet.yaml` results in `GitRepo` in `Ready` state.| :white_check_mark:|
|2|Test ability to check `waitForJobs` for `GitRepo` as `Ready` until the wait for job is finished. Verify that `sleep` time in `container` is greater than `timeoutSeconds: 120` in seconds, mentioned in the `fleet.yaml` results in `GitRepo` in `Ready` state. | :white_check_mark:|


**REPRO STEPS**

**Scenario 1**
1. As an admin user, add `GitRepo` which has `timeoutSeconds` `120seconds` mentioned in the `fleet.yaml`.
2. Navigated back to Rancher > Continuous Delivery.
3. Created a GitRepo using `https://github.com/sbulage/test-fleet` and path `/fleet-timeout`
5. Click on `<cluster-name>/workloads/jobs` and check the status of the pod created by the job.
5. Again check the status after the timeout seconds.
6. Verified that `Init Container` is created and Pod status is `Running`.

**Scenario 2**
1. As an admin user, add `GitRepo` which has `timeoutSeconds` `60seconds` mentioned in the `fleet.yaml`.
2. Navigated back to Rancher > Continuous Delivery.
3. Created a GitRepo using `https://github.com/sbulage/test-fleet` and path `/fleet-timeout`
4. Set `sleep` time greater than the `timoutSeconds`.
5. Click on `<cluster-name>/workloads/jobs` and check the status of the pod created by the job.
6. Wait for the `sleep` time to reach and go above to the `timeoutSeconds`.
7. Verified that `Init Container` is not created and shows `Terminated` state.

**Comment by sbulage** [comment]
Re-open: Understanding the corner cases around this issue.

**Comment by kkaempf** [comment]
`wait-for-jobs` is just an argument passed to the `helm` call. Default is off.

Further testing would actually test helm instead of fleet.

Dicussed during weekly meeting and agreed to close it.
