### ISSUE TITLE
Support bundle dependency

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/fleet#392]
Fleet needs the ability to define bundle dependency: bundle X can't be deployed/processed until its dependency bundle Y has been processed and ready.

**Comment by nickgerace** [comment]
## Validation

Validated by checking three methods

1. Create GitRepo CR with `dependsOn` in `fleet.yaml` and nothing else.
2. Create GitRepo CR with `dependsOn` in `fleet.yaml` after creating a GitRepo CR in an non-`Ready` state.
3. Create GitRepo CR with `dependsOn` in `fleet.yaml` after creating a successful GitRepo CR.

### Method One

Bundle becomes active even though the `dependsOn` field is populated. This works as intended since `dependsOn` only looks for bundles that exist.

![Screen Shot 2021-08-04 at 7 18 28 PM](https://user-images.githubusercontent.com/39320683/128267594-c4922a0d-2e34-4117-a2a5-c438a141f212.png)

### Method Two

Bundle with `dependsOn` is in an error state since the first bundle is in a non-`Ready` state. This works as intended.

![Screen Shot 2021-08-04 at 6 58 27 PM](https://user-images.githubusercontent.com/39320683/128267685-98ef6f81-7cdb-4424-82c9-d04c1a641b32.png)

### Method Three

Bundle with `dependsOn` deploys once the first bundle is in a `Ready` state. This works as intended.

![Screen Shot 2021-08-04 at 7 04 32 PM](https://user-images.githubusercontent.com/39320683/128267760-8a889624-f271-4c05-a99b-77df97c03698.png)

## Config

- local cluster
  - Docker (single-node): `20.10.7`
  - Image: `rancher/rancher:v2.6-head` (`e3316c9`)
- downstream cluster
  - DO Droplet: `g-2vcpu-8gb`
  - Provider: `RKE1`
  - Kubernetes: `v1.21.3`

**Comment by dsmithbauer** [comment]
@nickgerace @StrongMonkey First, thank you so much for the work on this new feature. I am very much looking forward to this rolling out in an upcoming stable release!

In reviewing the latest release candidate with this feature v0.3.6-rc9, I noticed that dependsOn does not seem to support waiting on Bundles that are deployed from other Git Repositories per the validation use case below:

> Method One

> Bundle becomes active even though the dependsOn field is populated. This works as intended since dependsOn only looks for bundles that exist.

In this implementation, it makes it much harder to divide Git infrastructure repositories into smaller chunks that can be deployed in different configurations to different clusters (using different labels, for example), reducing code duplication.

Given this hypothetical example, I think it would be beneficial to be able to `dependOn` bundles from different Git repos.

Git Repo 1: Common (Bundles include Docker Registry credentials, storage classes, etc.)
Git Repo 2 (depends on Bundles in repo 1): Prometheus (Bundles include Prom Operator and required CRDs)
Git Repo 3 (depends on Bundles in repo 2): Apps (app deployments that include Prometheus ServiceMonitor resources that will fail without the bundles from the first two repos)

So, essentially some of the bundles in repos 1, 2, and 3 will depend on bundles in the previously numbered Git repo - chained.
1 <- 2 <- 3

In a second cluster, I may want to swap out Git Repo 3 to deploy a separate set of applications that also require ServiceMonitor CRDs already be installed. Ideally, I would not want to have a single Git repo that includes all the Bundles for repos 1, 2, and 3, because now I need to duplicate all the code for repos 1 and 2 in the new 4th Git repo with the different apps.

One could potentially achieve reusability and reduce code duplication with Git submodules, but that can be cumbersome to maintain. I would like to see the ability to order deployments across Bundles deployed from different Git Repos when the previous Bundles do not exist using the `dependsOn` feature.

Thank you for your time and consideration of this request. Fleet is really awesome!

**Comment by StrongMonkey** [comment]
@dsmithbauer Thanks for your feedback! Yeah I think requiring the bundle that pre-exists doesn't make too much sense in multi-gitrepo use case as the bundle won't be created at the same time. cc @nickgerace what do you think?

**Comment by dsmithbauer** [comment]
> @dsmithbauer Thanks for your feedback! Yeah I think requiring the bundle that pre-exists doesn't make too much sense in multi-gitrepo use case as the bundle won't be created at the same time. cc @nickgerace what do you think?

In our scenario, they do get created at the same time because we apply multiple labels to the cluster at once (usually right after we create the cluster from scratch via automation).  Each label corresponds to a different Git repo (1, 2, 3, 4). Except, we'd like to be able to make sure that bundles in repo 1 still get applied before 2, and bundles in 2 still get applied be for 3 OR 4 (where we only apply a label to deploy apps from 3 or 4 - not both).  The difference is we don't have to duplicate all the code in Git repos 1 and 2 in both repos 3 and 4.

Worst case scenario, if we never applied the labels for repo 1 or 2, and applied the label for repo 3 or 4, they could sit there in error waiting on the required bundles to be deployed. To me, it seems like it would be desirable to have the same behavior you have implemented for bundles in the same repo implemented for bundles across all repos by their unique bundle names.

**Comment by dsmithbauer** [comment]
But, I think we are in agreement - lol.  Removing the bundle "pre-exists" condition and simply erroring if the bundle is not already deployed would work for both bundles deployed from the same repo and bundles deployed from different repos.

**Comment by nickgerace** [comment]
I agree with both of you; thanks for the comment @dsmithbauer. Would you mind creating an issue and linking it back here? I'd normally be happy to do it for you, but I want to ensure I do not botch wording and intent.
