### ISSUE TITLE
Feature Request - Global Secrets

### ISSUE THREAD

**Issue by wzrdtales** [rancher/fleet#412]
This is probably a feature request for rancher per se. It would be a very valuable feature to have a global secure secret store. This would allow also fleet to consume  secrets of common resources to be read safely and deployed. Right now somewhere in some automation script the plain password exists. That is of course something to avoid and have proper separation of concerns.

Would also fix https://github.com/rancher/fleet/issues/202

**Comment by philomory** [comment]
I think one pattern that could be used to address this would be to allow storing encrypted secrets within git repository, but having the Fleet Controller be responsible for decrypting them as it reads e.g. `fleet.yaml` (and possibly other files read via e.g. the `valuesFile` key), rather than passing the encrypted data verbatim to the downstream clusters and expecting them to figure things out.

One option would be to overhaul the existing SOPS integration in Fleet, but provide the option to have the Fleet controller be responsible for decrypting the secrets (as well as providing the option to configure e.g. what provider is used for the actual encryption and decryption).

Another option would be integrating [vals](https://github.com/variantdev/vals). This would allow you to reference secrets stored in a number of ways, including:
* You can store them in a SOPS-encrypted file, and then reference them in `fleet.yaml` via e.g. `my_key: ref+sops://path/to/file#/foo/bar`. This gives you access to all of SOPS's supported encryption methods.
* You can store the secret data itself somewhere like Hashicorp Vault or AWS Secrets Manager, and then reference it via e.g. `my_key: ref+vault://mykv/foo#/bar?address=https://vault1.example.com:8200`

**Comment by mjaggard** [comment]
Alternatively an integration with Sealed Secrets https://github.com/bitnami-labs/sealed-secrets might work nicely. The only big challenges I can see is distributing keys both initially and at secret rotation. It's relatively nice to use because the public key can be quite easily accessible.

**Comment by skaven81** [comment]
An approach I could make use of, would be to give the `fleet.yaml` a section describing file decryption.  In the simplest case, it would be a list of filenames within the Bundle that need to be decrypted, along with the name of a key used to decrypt them.

The key would be stored in a Secret in the `fleet-system` namespace on the Rancher master, where `fleet-controller` and `gitjob` run.  The Fleet controller would read a Secret (or perhaps secrets) that associate `name=<key>`.  When Fleet prepares a Bundle, it examines the `fleet.yaml`, sees that it has files to decrypt, and then uses the appropriate key to do so.  Any overlays or Helm operations are executed _after_ the decryption is done, so that overlays can be mostly in plain text.

This arrangement would ensure that Secrets (and anything else that needs to be hidden) can be stored as encrypted blobs in the Git repository, without having to store the key in plaintext anywhere in Git.

A variant of this approach could be to include the key in the `GitRepo` resource itself as part of its spec.  And this might be just as secure for some implementations, since `GitRepo` resources only exist in the Rancher/Fleet master cluster, which should be locked down.  However, it's likely to be common in the future for people to use GitOps to manage their `GitRepo` resources too -- in which case now you have the "where do you put the key" problem again.  Allowing users to either put the key in the `GitRepo` resource, or have the `GitRepo` resource (and/or the `fleet.yaml`) make a reference to a Secret that only the Fleet controller can see, would give us the most flexibility in this approach.

**Comment by strowi** [comment]
Also looking for a solution to this. Currently pre-deploying some central secrets with terraform on cluster-creation. But sth. like argocd's plugin-system with git-crypt would be really nice.

**Comment by kkaempf** [comment]
See #144

**Comment by wzrdtales** [comment]
i guess there is a reason why fleet is loosing to flux.
