### ISSUE TITLE
fleet-controller fails to communicate with rancher API: x509 certificate signed by unknown authority

### ISSUE THREAD

**Issue by mjeco** [rancher/fleet#418]
I'm getting the following x509 certificate error on fleet-controller for all my downstream clusters which is preventing fleet-agent deployment.

```
time="2021-06-15T12:22:46Z" level=error msg="error syncing 'fleet-default/c-jf77d': handler import-cluster: Get \"https://rancher.cattle-system/k8s/clusters/c-jf77d/version?timeout=15s\": x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate \"dynamiclistener-ca\"), requeuing"
```

Rancher API is using some dynamically generated certificated signed by `CN = dynamiclistener-ca,O = dynamiclistener-org`

How to configure fleet-controller to trust this certificate?

Rancher: v2.5.8
Fleet: v0.3.5

**Comment by mjeco** [comment]
I fixed the issue myself. The problem was with the TLS secrets in `cattle-system` namespace. Fleet uses CA cert from secret `tls-rancher-internal-ca` while the Rancher server uses CA from secret `tls-rancher`. For some reason on our Rancher instance, the certificates in those two secrets were not the same. To fix the fleet issue, I copied the certs from `tls-rancher` secret into `tls-rancher-internal-ca` and it worked.

**Comment by Himansh-ilink** [comment]
Hello @mjeco 
We have installed rancher using k3s cluster and we have 2.6.3 rancher version. We are using letsencrypt ssl in our rancher domain. In fleet-controller pod, we are getting error like this.

level=error msg="error syncing 'fleet-default/c-rbs74': handler import-cluster: Get \"https://10.43.208.104/k8s/clusters/c-rbs74/version?timeout=15s\": x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate \"dynamiclistener-ca\"), requeuing"

And in downstream cluster we are getting below error.

Get "https://10.43.208.104/k8s/clusters/c-rbs74/version?timeout=15s": x509: certificate signed by unknown authority (possibly because of "x509: ECDSA verification failure" while trying to verify candidate authority certificate "dynamiclistener-ca").

As you mentioned above, I checked tls-rancher and tls-rancher-internal-ca and in our case both have same certs data.

Can you please help us.

Thank you 
Himanshu

**Comment by Shaked** [comment]
@mjeco thank you for this. Is there a reason why this happens? Why the certs are different? Using Rancher 2.5.8

**Comment by strowi** [comment]
ran into sth. similar when switching from a self-signed certificate to letsencrypt. Had to update the kubeconfig data in the secret `cattle-fleet-system/fleet-agent` on all downstream-clusters (removing the certificate-data).

**Comment by whu-viasat** [comment]
> ran into sth. similar when switching from a self-signed certificate to letsencrypt. Had to update the kubeconfig data in the secret `cattle-fleet-system/fleet-agent` on all downstream-clusters (removing the certificate-data).

Is there a way to do this seamlessly without going on each downstream cluster and updating the fleet-agent secret one by one? My use case is I have too many downstream clusters and when switching from private CA to let's encrypt, new fleet-agent pod can't talk to Rancher anymore because the downstream fleet-agents are holding old private CA cert
