### ISSUE TITLE
Allow helm charts to be fetched as tgz from git and remove the need to extract them

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/fleet#452]
At the moment it is required to extract helm charts when they are stored and deployed from git.

It would be great if we could utilize helm charts from git also in compressed format.

So specifying this in fleet.yaml:
chart: ./my-chart.tgz

instead of the extracted subdir
chart: ./my-chart

**Comment by nickgerace** [comment]
This would likely work by checking "if input not directory and is archived and/or compressed". I like this idea a lot.

**Comment by kkaempf** [comment]
not planned

**Comment by jdloft** [comment]
> not planned

Ok then this needs to be made clear because currently the [fleet.yml reference](https://fleet.rancher.io/gitrepo-structure#reference) says:
```
  # A https URL to a Helm repo to download the chart from. It's typically easier
  # to just use `chart` field and refer to a tgz file.
```

It sounds like this was supported/planned at one point and was just dropped. I think at one point I was also able to run a `fleet test -f` with a `fleet.yml` that referred to a `.tgz` and it rendered the chart just fine.
