### ISSUE TITLE
Add `values.yaml` order of acceptance to docs 

### ISSUE THREAD

**Issue by nickgerace** [rancher/fleet#543]
Currently, users may have to parse Fleet code to learn the order of which `values.yaml` augmentations are accepted (e.g. valuesFiles while editing `values.yaml` somewhere else). We should document the order of acceptance for these values.

**Comment by gregsidelinger** [comment]
I would like to see the values from the fleet.yaml also override the valuesFiles from fleet.yaml.  I like to have a fully functioning values.yaml files and then override any cluster specific stuff in the values section of the fleet.yaml using values pulled in from cluster labels.   Trying to keep any fleet specific logic out of my generic values files so that they can be tested and ran outside of fleet.

**Comment by nickgerace** [comment]
This docs change would illustrate what happens when multiple sources provide `values.yaml` changes.

**Comment by StrongMonkey** [comment]
@jtravee We can document the following behavior after this section https://fleet.rancher.io/gitrepo-structure/#reference, maybe as a tip

> Helm values are applied in the following order: helm.values -> helm.valueFiles -> helm.valuesFrom.
