### ISSUE TITLE
Fleet consistently listing bundledeployments

### ISSUE THREAD

**Issue by dramich** [rancher/fleet#553]
Based on API server metrics it appears fleet is listing bundledeployments consistently. This should be investigated and potentially moved to a cache or watch. 

This setup has about 300 downstream imported clusters. 

![Prometheus - API Server - Post Restart](https://user-images.githubusercontent.com/13897607/135323635-3901d48e-9002-48f8-aeb8-5766031ed7af.png)

**Comment by moio** [comment]
@dramich can you share details about the test setup, and specifically, what fleet version is under test there?

**Comment by manno** [comment]
This is fixed by https://github.com/rancher/fleet/pull/1485 ?

**Comment by moio** [comment]
> This is fixed by #1485 ?

I do not think so.

Given peaks happen every 5 minutes I wonder whether they come from:

https://github.com/rancher/fleet/blob/f8d55c86ef7b487baa4b82573cbac2945613fd21/pkg/controllers/content/controller.go#L54-L64

Because `ContentPurgeInterval` is 5 minutes and `List()` is called instead of `Cache().List()` aka the plain `Client` is used instead of the `Informer`.

@dramich I could create a PR/patched image to find out if you are willing to test it.

**Comment by manno** [comment]
This should be fixed by
https://github.com/rancher/fleet/issues/1980
