### ISSUE TITLE
Add label-based bundle dependency

### ISSUE THREAD

**Issue by nickgerace** [rancher/fleet#563]
Currently bundle's can have dependency based on name of other bundles. We need to add the following:

- Ability to use bundle labels for defining dependencies: This makes it easy to handle multiple bundles via matching labels in place of naming bundles in advance.
- Ability to define custom labels on your bundles
- Ability to define a custom bundle name, rather than combination of bundleName-Path when used directly or GitRepo-Path when consumed via continuous delivery.

**Comment by nickgerace** [comment]
Available on Rancher v2.6-head in Fleet v0.3.8-rc1

**Comment by StrongMonkey** [comment]
@davidnuzik Bundle are created under GitRepo. For example, if you create a Gitrepo with https://github.com/rancher/fleet-examples and `multi-cluster/helm` as path, then fleet will try to read content from `multi-cluster/helm` and create a bundle(fleet CRD) that has all the necessary information in it. See more information about https://fleet.rancher.io/concepts/. You can think of it as a bunch of k8s manifests.

BundleDependency means that user can define dependency bewteen bundles. Let's say you defined a gitrepo https://github.com/rancher/fleet-examples with two paths `multi-cluster/helm` and `multi-cluster/manifest`, called bundle A and bundle B. You want bundle A to be deployed into cluster first before bundle B can be deployed. This is how BundleDependency comes into play. Today you can define bundleDependency by referencing names on fleet.yaml (Check dependsOn field on this [referennce doc](https://fleet.rancher.io/gitrepo-structure/#reference))

So this issue is to validate three parts:
1. You should be able to add labels(metadata.labels) through fleet.yaml. The label will be reflected on the bundle yaml when you view yaml in UI.
2.  You should be able to configure bundle name through fleet.yaml. By default bundle name is generated with a combination of gitRepo and path name as prefix, but this can be configured from fleet.yaml now. 

To configure name and labels, simply add these two fields into `fleet.yaml`:
```
name: my-bundle-name
labels:
  foo: bar
```
3. You should be able to set dependency by specifying the name of the bundle or any bundle that matches a label selector. This will make sure that the bundle you depend on will be deploy before your bundle can be deployed. Here is an example of setting this:
```

# dependsOn allows you to configure dependencies to other bundles. The current bundle
# will only be deployed, after all dependencies are deployed and in a Ready state.
dependsOn:
  # Format: <GITREPO-NAME>-<BUNDLE_PATH> with all path separators replaced by "-" 
  # Example: GitRepo name "one", Bundle path "/multi-cluster/hello-world" => "one-multi-cluster-hello-world"
  - name: one-multi-cluster-hello-world
  # Select bundles to depend on based on their label.
  - bundleSelector:
      matchLabels:
        app: weak-monkey
```

**Comment by davidnuzik** [comment]
**My checks PARTIALLY FAILED**
I tested by forking fleet-examples and creating a branch to contain my modifications for testing this issue (as seen here https://github.com/davidnuzik/fleet-examples/tree/fleet-563). 
Everything worked, except that if I attempt to specify `dependsOn` and select for matching labels this doesn't seem to work. `dependsOn` only seems to work for me if I provide the name of the bundle. 
 
**Reproduction Steps:**

Not required. This is a new change/enhancement that is being validated here.

-----
 
**Validation Environment:**

Rancher version: v2.6-head `96e2438` 11/17/2021 (fleet v0.3.8-rc1)
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: rke2
Downstream K8s version: v1.21.6+rke2r1
 
**Validation steps:**

0. Provision three clusters each with sufficient resources and each with the correct `env=foo` label for the multi-cluster examples (env=test, env=dev, env=prod). The prod cluster should have cloud set up correctly so LB's can be provisioned
1. Fork fleet-examples and create a branch. In this branch I will modify `/multi-cluster/helm/fleet.yml` and `/multi-cluster/manifests/fleet.yaml` in order to validate these changes.
a. I modified the helm fleet.yml such that it defines a name in it (which names the Bundle object) and I also specified labels. The file was modified to add a few new lines above like:
```
name: dave-custom-mc-helm-example
labels:
  tacos: rule
```

   b. I modified the manifests fleet.yaml such that it `dependsOn` the helm fleet bundle. This validates that we can first select for a bundle name. Then in future steps I mention I modify this again so we only select via labels.

```
dependsOn:
  - name: dave-custom-mc-helm-example
```
2. Create a Git Repo object in the Rancher UI. Fill in the following fields on the form and submit to create the Git Repo object / abstraction.
a. name = provide any name. I provided `dave563`. This will not be leveraged by fleet since we are specifying the name (at least for the helm mc example). And since we select for the name specified in the helm mc fleet.yml example or the labels later, the name isn't relevant here.
b. git repo = `https://github.com/davidnuzik/fleet-examples`
c. branch = `fleet-563`
d. add a path. for this first path, enter a value of `/multi-cluster/manifests`
e. add another path. for this second path, enter a value of `/multi-cluster/helm`
f. Submit to create the git repo object.
3. Quickly navigate to the Bundles page in the Rancher UI (Advanced>Bundles) notice that:
a. Fleet correctly creates the "dave-custom-mc-helm-example" bundle, as specified in the fleet.yml name (if it had not, it would be named "dave563-multi-cluster-helm" as this is the default naming mechanism Rancher uses).
![image](https://user-images.githubusercontent.com/45179589/142477434-6fd837b1-cc31-4867-b0ff-7748e8145e03.png)

b. Fleet puts the "dave563-multi-cluster-manifests" Bundle in an Error State since it is waiting for the "dave-custom-mc-helm-example" Bundle to be in a Ready state. This is good, this proves that the `dependsOn` specification worked. It searched/selected for the name I specified and waited until the deployment was ready. In the UI I see the following bundleStates, as expected:
![image](https://user-images.githubusercontent.com/45179589/142477373-ec45700f-4814-4585-aa87-cf2151d13bb0.png)
c. I observed the "dave-custom-mc-helm-example" Bundle become ready and Active, and then the manifests bundle was created once that was ready, as expected. Now both bundles are Active/Ready, as expected.
![image](https://user-images.githubusercontent.com/45179589/142477658-2de68c1f-70f6-4eb3-b733-7cd4d2b8969d.png)
4. Delete the Git Repo object. This correctly tears down all deployments/services/etc. Deleting the Git Repo is probably not necessary, but it should make it easier for me to observe the order of operations -- I should be able to more easily see the helm example get created first, then the manifests example.
5. Modify `/multi-cluster/manifests/fleet.yml` again. This time removing the name of the bundle and instead just selecting for the labels set. Create the Git Repo object again in the Rancher UI, using the same exact entries in the fields as before. Create the object. Observed different behavior in this case (Which is NOT EXPECTED). I saw both the repos try to deploy at the same excact time, as if `dependsOn` was ignored. I supplied my environment to Daishan to review at his request.

```
dependsOn:
  - bundleSelector:
      matchLabels:
        tacos: rule
```

**Comment by davidnuzik** [comment]
**My checks PASSED** on a second attempt by just modifying the `bundleSelector` to instead be `selector` like as follows in the manifests fleet.yaml:

```
dependsOn:
  - selector:
      matchLabels:
        tacos: rule
```

Upon deleting the git repo, making this change, adding it again. I saw proper rollout just like before when depending on a specific bundle name in validation step 1b.
