### ISSUE TITLE
Question: Possibility to ignore git submodules?

### ISSUE THREAD

**Issue by patrijua** [rancher/fleet#586]
We have a git repository with several submodules. How to configure Fleet NOT to make git submodule update? With current SSH keys provided to Fleet, it does not have access to those submodules thus making container step-git-source to fail. There's no need for Fleet to have access to any of those submodules.  It should be possible to configure Fleet not to update submodules. Is this already possible?

**Comment by nickgerace** [comment]
I think the resolution of this issue would solve this one.
https://github.com/rancher/fleet/issues/583

**Comment by kkaempf** [comment]
see #583

**Comment by niklastreml** [comment]
I'm currently running into an issue similar to @patrijua. I'm trying to rollout a gitrepo, that has multiple submodules from other git hosts, which gitcloner is not allowed to reach. When cloning the repo, gitcloner runs into a timeout, when recursively cloning the modules. 

I don't think it is currently possible to override this behaviour, since https://github.com/rancher/fleet/pull/2557 was merged. [Gitcloner](https://github.com/rancher/fleet/blob/main/internal/cmd/cli/gitcloner/cloner.go#L82) uses the default recursion depth, without a way to override this setting.
