### ISSUE TITLE
Fleet agent error: "rpc error: code = ResourceExhausted"

### ISSUE THREAD

**Issue by topperblues** [rancher/fleet#691]
Hi everyone, for a few days I have not been able to run fleet-agent.
Every time I run the force update on the git repo, the fleet-agent (fleet container) goes into error:
```
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_SERVICE_PORT=443
HOSTNAME=novatellus-fe-staging-51956-zvnnm
COMMIT=74d805caf5ae5a36e443afbaba2e5917bbb1effd
PWD=/workspace/source
EVENT_TYPE=
HOME=/home/fleet-apply
KUBERNETES_PORT_443_TCP=tcp://10.43.0.1:443
ARCH=amd64
SHLVL=1
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_ADDR=10.43.0.1
KUBERNETES_SERVICE_HOST=10.43.0.1
KUBERNETES_PORT=tcp://10.43.0.1:443
KUBERNETES_PORT_443_TCP_PORT=443
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/env
time="2021-12-27T09:35:06Z" level=fatal msg="rpc error: code = ResourceExhausted desc = trying to send message larger than max (2460336 vs. 2097152)"
```

I have tried everything, even `docker system prune`, but I can't resolve.
This is the only error I have, I have no other containers or pods in error.

Do you have any suggestions?
Thank you.

**Comment by Sparkz0629** [comment]
@topperblues ,  we are experiencing the same issue.
How did you manage to resolve it?

**Comment by davidy718** [comment]
we are experiencing the same issue.
How did you manage to resolve it?

**Comment by puffitos** [comment]
> we are experiencing the same issue. How did you manage to resolve it?

@davidy718 like I mentioned, the problem arose because the bundle handled 2 different versions of the chart. Our solution was to create a dedicated branch for that new version (where **all** customizations would have the same version) and deploy that branch only in the clusters, where we wanted to try the new version. Once everything was tested in dev, we moved the same branch to staging and then just merged it to main.

The branch name's was `cool-update`. We worked forward as follows:

1. Dev GitRepo is set to use the `cool-update` branch. Deployment works fine.
2. Staging GitRepo is set to use the `cool-update` branch as well. Deployment works fine there as well.
3. We open a PR to merge `cool-update` to main: Prod GitRepo deploys the main branch. Everything works well (in most cases 😂 )
4. We change the Dev and Staging GitRepos to point to the main branch again.

**Comment by sabuhish** [comment]
Hello, anyone else facing this issue?

We are deploying the GitLab Helm chart (v9.9.0) using Fleet v0.14.2 and hitting the hardcoded 2MB gRPC limit:
rpc error: code = ResourceExhausted desc = trying to send message larger than max (2111012 vs. 2097152)


We have tried:

- Splitting subcharts (runner, redis, postgres) into separate Fleet bundles, no meaningful size reduction since Fleet still downloads and bundles the entire umbrella chart
- Removing diff.comparePatches
- Consolidating overlays
- Moving values inline vs valuesFiles

Referencing issue #2442 which was closed without resolution.

**Comment by kkaempf** [comment]
#2442's resolution is [here](https://github.com/rancher/fleet/issues/2442#issuecomment-2137461215) 😉 
Either split your bundle or move to [OCI storage](https://fleet.rancher.io/0.14/how-tos-for-users/oci-storage).
Alternatively, you can try to increase etcd's request limit even further.

**Comment by sabuhish** [comment]
Thank you @kkaempf, will have a look to that! :)
