### ISSUE TITLE
Namespace creation fails if cluster name isn't valid RFC 1123

### ISSUE THREAD

**Issue by thedadams** [rancher/fleet#739]
If a cluster name isn't valid RFC 1123 (for example, if it has dots (`.`) in it), then the namespace fleet-controller tries to create will fail to create with an error like ` a lowercase RFC 1123 label must consist of lower case alphanumeric characters or '-'`.

It seems that fleet-controller should sanitize the cluster name before creating the namespace.

**Comment by mattfarina** [comment]
I think the question to work out with provisioning is whether Fleet should:
1. sanitize the name to make it safe for namespace creation
2. detect the name for the namespace is not valid and return an error rather than try to create the namespace

With a separation of concerns in mind, I would have fleet detect the invalid name and return an error without trying to create the namespace. Provisioning would then need to make sure a valid name is passed. This makes the API contract between fleet and provisioning clear and doesn't mix provisioning specific logic in to fleet.

**Comment by olblak** [comment]
I would also be in favor to return an error instead of sanitizing the name of the namespace.

**Comment by manno** [comment]
`Cluster` and `ClusterRegistrationToken` resources can no longer contain invalid (https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names) chas in their names. Their names are used to generate other resources, like the service account and the cluster registration namespace. With the new OpenAPI schema validations, this issue is fixed.

**Comment by izaac** [comment]
Imported clusters can have `.` in their name and this is still valid in Rancher `v2.6.9-rc2`

![Image](https://user-images.githubusercontent.com/27659/193152903-6f589d70-0cde-44aa-9f98-57d15b6d2ad9.png)

**Comment by Jono-SUSE-Rancher** [comment]
Realistically there is no way for this to go into v2.6.9 at the moment, so I am going to move it out. My recommendation would be to fix it in the next 2.7 release and backport to 2.6x or if it doesn't require a Rancher release, perhaps you can work in an OOB fix.

**Comment by mattfarina** [comment]
@izaac and @Jono-SUSE-Rancher I think I see where the problem is. This was tested within Rancher. Fleet and provisioning have their own unique cluster CRDs for clusters. The Fleet one has been updated to not allow `.` in the name. But, it appears provisioning allows clusters to be created with the `.` and provisioning will try to create a fleet cluster instance with the `.` that fails. That happens [here](https://github.com/rancher/rancher/blob/78c7ac0187169c67b844c966691a5e5c53a4acc9/pkg/controllers/provisioningv2/fleetcluster/fleetcluster.go#L120).

@izaac can you test the fleet part directly without doing it through Rancher?

@Jono-SUSE-Rancher how do we get provisioning to tackle their part in this?

**Comment by izaac** [comment]
Created the Rancher Issue
https://github.com/rancher/rancher/issues/39248

**Comment by izaac** [comment]
@mattfarina I tried testing using a yaml to bypass the UI as suggested:

Applying with cluster name `mytestcluster.1`

```
k apply -f fleet-cluster.yaml
The Cluster "mytestcluster.1" is invalid: metadata.name: Invalid value: "mytestcluster.1": metadata.name in body should match '^[-a-z0-9]+$'
```

Applying with cluster name `Mytestcluster.1`
```
k apply -f fleet-cluster.yaml
The Cluster "Mytestcluster.1" is invalid:
* metadata.name: Invalid value: "Mytestcluster.1": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
* metadata.name: Invalid value: "Mytestcluster.1": metadata.name in body should match '^[-a-z0-9]+$'
```


Using `mytestcluster-1` (with a dash) works.


Sample YAML

```yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    objectset.rio.cattle.io/id: fleet-cluster
    objectset.rio.cattle.io/owner-name: mytestcluster-1
    objectset.rio.cattle.io/owner-namespace: fleet-default
  labels:
    management.cattle.io/cluster-display-name: mytestcluster-1
    provider.cattle.io: rke2
  name: mytestcluster-1
  namespace: fleet-default
```

**Comment by thardeck** [comment]
Many thanks for verifying.
